### PR TITLE
Updating mac icons so retina and non-retina icons are the same

### PR DESCRIPTION
**Pull request by cyphun**
This makes the non-retina icons look the same as the retina icons for the Mac. This way there is more constancy on what icon to look for in the menu bar.

### CODE REVIEW

**Comment by stevschmid** [comment]
Did you verify that it looks good?

**Comment by cyphun** [comment]
I did, I checked both the white and black icons. It looks really close to the retina icons.

**Comment by stevschmid** [comment]
Thanks mate!

**Comment by cyphun** [comment]
No problem, glad to help out.

**Pull request merged**
