### PR TITLE
send oppName in result

### PR DESCRIPTION
**Pull request by mharris717**
Not suggesting you merge this, I'm sure there is a ton wrong with it, I barely know C++ anymore. 

I'd like to be able to log the opponent's name, and see their name in the game display on the website.

I can't speak to what happens after the JSON hits your server, but up to that point this does seem to work.

The matching regex is terrible, should be better, and gamertag's can probably have other characters in them. 

I have two reasons for wanting to log opponent's name:
- Helpful to find people you played previously, etc
- Could enable use of Track-o-Bot as an automatic reporting tool for tournaments.

### CODE REVIEW

**Comment by djnym** [comment]
I used to use hearthstats and it's uploader contained the opponents name.  It was useful only if I queued up twice against them (since I rarely look at the name otherwise).  So while I don't care too much if it made it to the website, I do think it would be cool to see it in the log.

**Comment by Probeus** [comment]
Only visisting because I noticed the tracking missed opponentname. Would love to see this implemented!

**Comment by alexweber** [comment]
:+1: this would be really helpful for automatic tournament reporting

**Comment by stevschmid** [comment]
I'll look into this for a future release.

**Comment by stevschmid** [comment]
No names for now.

**Pull request closed without merging**
